services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false # Disable security for local development
      - xpack.monitoring.collection.enabled=true
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - microservices-net
  logstash:
    container_name: logstash
    image: logstash:8.17.1
    volumes:
      - ./logstash/:/logstash_dir
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    networks:
      - microservices-net
    restart: unless-stopped
  kibana:
    container_name: kibana
    image: kibana:8.17.1
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - microservices-net
    restart: unless-stopped
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres: {}
  elastic_data: {}