server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
      format_sql: true
  # Enable Feign's Resilience4j integration
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1spgkyzchsjzz7md.us.auth0.com/
          audiences:
            - https://dev-1spgkyzchsjzz7md.us.auth0.com/api/v2/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
    instances:
      default:
        base-config: default
        wait-duration: 500ms
      userServiceRetry:
        base-config: default
        wait-duration: 200ms
  ratelimiter:
    instances:
      default:
        limit-for-period: 1
        limit-refresh-period: 5s
        timeout-duration: 1ms
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 20
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 0.1

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: /user-service/api-docs